.\" cfetch
.TH cfetch  "1" "December, 8 2020" "cfetch" "cfetch manpage"

.SH NAME
cfetch - A simple system information tool for Linux.


.SH DESCRIPTION
A simple system information tool for Linux. cfetch displays the systems username, host, os, kernel, computer model, cpu, ram, shell, numbers of packages installed, and uptime information.


.SH CURRENTLY SUPPORTED DISTROS
Alpine Linux, ArchBang, Arch Linux, ArcoLinux Artix Linux, CentOS, Debian, Devuan, elementary OS, Fedora, Gentoo Linux, gNewSense, GNU Guix, Hyperbola GNU/Linux-libre, instantOS, KISS Linux, Linux Lite, Linux Mint, Mageia, Manjaro, MX Linux, NixOS, openSUSE, Parabola GNU/Linux-libre, Pop!_OS, PureOS, Raspbian, Slackware, Ubuntu (and its flavours), Void Linux, and Voyager Live.


.SH CFETCH CONFIGURATION
Git clone the cfetch repository:
    git clone https://github.com/clieg/cfetch.git

Compile cfetch
    make compile

Install cfetch
    sudo make install

Run cfetch
    cfetch

Uninstall cfetch
    sudo make uninstall


.SH AUTHOR
Copyright (c) 2020 - 2021 Clint <https://github.com/clieg>


.SH LICENSE
This programme is provided under the GPL-3.0 License. See LICENSE <https://github.com/clieg/cfetch/blob/master/LICENSE> for more details.


.SH CREDITS
ufetch <https://gitlab.com/jschx/ufetch>: ASCII Distro logos

Thanks to cfetch contributors ♥ <https://github.com/clieg/cfetch/graphs/contributors>
